# Generated by Django 2.2.6 on 2023-03-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220225_0322'),
        ('posts', '0002_auto_20220118_2143'),
        ('posts', '0009_auto_20220414_1818'),
    ]

    operations = [
    ]
